In [3]:
%pip install psycopg2-binary sqlalchemy pandas

Requirement already satisfied: psycopg2-binary in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (2.9.11)
Requirement already satisfied: sqlalchemy in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (2.0.44)
Requirement already satisfied: pandas in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (2.2.3)
Requirement already satisfied: typing-extensions>=4.6.0 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from sqlalchemy) (4.15.0)
Requirement already satisfied: numpy>=1.26.0 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from pandas) (2.2.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/oulayabenani/Library/Python/3.13/lib/python/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from pandas) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from pandas) (2024.2)
Requirement already satisfied: six>=1.5 in /Users/oulayabenani/Library/Python/3.13/lib/python/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 25.1.1 -> 25.3
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [ ]:
from sqlalchemy import create_engine
import pandas as pd

#connexion
engine = create_engine("postgresql://postgres:postgres@localhost:5432/postgres")

In [ ]:
from sqlalchemy import text

with engine.connect() as conn:
    print("connexion successfull:")
    result = conn.execute(text("SELECT version();"))
    print(result.fetchone())

✅ Connexion réussie ! Version PostgreSQL :
('PostgreSQL 15.14 (Debian 15.14-1.pgdg13+1) on aarch64-unknown-linux-gnu, compiled by gcc (Debian 14.2.0-19) 14.2.0, 64-bit',)

In [ ]:
from sqlalchemy import text

schema_sql = """
CREATE TABLE customers (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  join_date DATE NOT NULL
);

CREATE TABLE categories (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL
);

CREATE TABLE products (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  price NUMERIC NOT NULL,
  category_id TEXT REFERENCES categories(id)
);

CREATE TABLE orders (
  id TEXT PRIMARY KEY,
  customer_id TEXT REFERENCES customers(id),
  ts TIMESTAMPTZ NOT NULL
);

CREATE TABLE order_items (
  order_id TEXT REFERENCES orders(id),
  product_id TEXT REFERENCES products(id),
  quantity INT NOT NULL,
  PRIMARY KEY (order_id, product_id)
);

CREATE TABLE events (
  id TEXT PRIMARY KEY,
  customer_id TEXT REFERENCES customers(id),
  product_id TEXT REFERENCES products(id),
  event_type TEXT CHECK (event_type IN ('view','click','add_to_cart')),
  ts TIMESTAMPTZ NOT NULL
);
"""


with engine.begin() as conn:
    for statement in schema_sql.split(";"):
        if statement.strip():
            conn.execute(text(statement))

print("tables created")

ProgrammingError: (psycopg2.errors.DuplicateTable) relation "customers" already exists

[SQL:
CREATE TABLE customers (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  join_date DATE NOT NULL
)]
(Background on this error at: https://sqlalche.me/e/20/f405)

In [ ]:
drop_sql = """
DROP TABLE IF EXISTS order_items;
DROP TABLE IF EXISTS orders;
DROP TABLE IF EXISTS events;
DROP TABLE IF EXISTS products;
DROP TABLE IF EXISTS categories;
DROP TABLE IF EXISTS customers;
"""

from sqlalchemy import text

with engine.begin() as conn:
    for statement in drop_sql.split(";"):
        if statement.strip():
            conn.execute(text(statement))

print("tables deleted, all good")

🧹 Tables supprimées avec succès !

In [ ]:
from sqlalchemy import text

schema_sql = """
CREATE TABLE customers (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  join_date DATE NOT NULL
);

CREATE TABLE categories (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL
);

CREATE TABLE products (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  price NUMERIC NOT NULL,
  category_id TEXT REFERENCES categories(id)
);

CREATE TABLE orders (
  id TEXT PRIMARY KEY,
  customer_id TEXT REFERENCES customers(id),
  ts TIMESTAMPTZ NOT NULL
);

CREATE TABLE order_items (
  order_id TEXT REFERENCES orders(id),
  product_id TEXT REFERENCES products(id),
  quantity INT NOT NULL,
  PRIMARY KEY (order_id, product_id)
);

CREATE TABLE events (
  id TEXT PRIMARY KEY,
  customer_id TEXT REFERENCES customers(id),
  product_id TEXT REFERENCES products(id),
  event_type TEXT CHECK (event_type IN ('view','click','add_to_cart')),
  ts TIMESTAMPTZ NOT NULL
);
"""

#we separate each command and execute them
with engine.begin() as conn:
    for statement in schema_sql.split(";"):
        if statement.strip():
            conn.execute(text(statement))

print("Tables created")

Tables created

In [ ]:
from sqlalchemy import text

seed_sql = """
INSERT INTO customers VALUES
('C1','Alice','2024-01-02'),
('C2','Bob','2024-02-11'),
('C3','Chloé','2024-03-05');

INSERT INTO categories VALUES
('CAT1','Electronics'),('CAT2','Books');

INSERT INTO products VALUES
('P1','Wireless Mouse',29.99,'CAT1'),
('P2','USB-C Hub',49.00,'CAT1'),
('P3','Graph Databases Book',39.00,'CAT2'),
('P4','Mechanical Keyboard',89.00,'CAT1');

INSERT INTO orders VALUES
('O1','C1','2024-04-01T10:15:00Z'),
('O2','C2','2024-04-02T12:30:00Z'),
('O3','C1','2024-04-05T08:05:00Z');

INSERT INTO order_items VALUES
('O1','P1',1),('O1','P2',1),('O2','P3',1),
('O3','P4',1),('O3','P2',1);

INSERT INTO events VALUES
('E1','C1','P3','view','2024-04-01T09:00:00Z'),
('E2','C1','P3','click','2024-04-01T09:01:00Z'),
('E3','C3','P1','view','2024-04-03T16:20:00Z'),
('E4','C2','P2','view','2024-04-03T12:00:00Z'),
('E5','C2','P4','add_to_cart','2024-04-03T12:10:00Z');
"""

with engine.begin() as conn:
    for statement in seed_sql.split(";"):
        if statement.strip():
            conn.execute(text(statement))

print("all good")

✅ Données insérées avec succès !

In [ ]:
import pandas as pd

for table in ["customers", "categories", "products", "orders", "order_items", "events"]:
    df = pd.read_sql(f"SELECT * FROM {table}", engine)
    print(f"\n Table {table}")
    display(df)

🧱 Table customers

   id   name   join_date
0  C1  Alice  2024-01-02
1  C2    Bob  2024-02-11
2  C3  Chloé  2024-03-05

🧱 Table categories

     id         name
0  CAT1  Electronics
1  CAT2        Books

🧱 Table products

   id                  name  price category_id
0  P1        Wireless Mouse  29.99        CAT1
1  P2             USB-C Hub  49.00        CAT1
2  P3  Graph Databases Book  39.00        CAT2
3  P4   Mechanical Keyboard  89.00        CAT1

🧱 Table orders

   id customer_id                        ts
0  O1          C1 2024-04-01 10:15:00+00:00
1  O2          C2 2024-04-02 12:30:00+00:00
2  O3          C1 2024-04-05 08:05:00+00:00

🧱 Table order_items

  order_id product_id  quantity
0       O1         P1         1
1       O1         P2         1
2       O2         P3         1
3       O3         P4         1
4       O3         P2         1

🧱 Table events

   id customer_id product_id   event_type                        ts
0  E1          C1         P3         view 2024-04-01 09:00:00+00:00
1  E2          C1         P3        click 2024-04-01 09:01:00+00:00
2  E3          C3         P1         view 2024-04-03 16:20:00+00:00
3  E4          C2         P2         view 2024-04-03 12:00:00+00:00
4  E5          C2         P4  add_to_cart 2024-04-03 12:10:00+00:00